#!/usr/bin/perl

$block=0;
while(!eof(STDIN)) {
  print "    $block\n";
  print "----------------------------------------------------------------\n";
  $block++;
  for($j=0;$j<16;$j++) {
    for($i=0;$i<64;$i++) {
      read(STDIN, $ln, 1);
      if(unpack("C", $ln)>=250) {
        print " ";
      } else {
        print $ln;
      }
    }
    print "\n";
  }
  print "----------------------------------------------------------------\n";
}


